version = 0.1
default-task = 'build'

[env]
BIN_PATH = '~/bin/'

[[task]]
name = 'install'
dep = 'dist/jspm.exe'
run = 'cp dist/jspm.exe ${{ BIN_PATH }}/jspm.exe'

[[task]]
name = 'build'
deps = ['dist/jspm.exe']

[[task]]
target = 'appmap.json'
run = 'deno run --unstable -A --importmap appmap.json src/jspm.js install -m appmap.json -e source'

[[task]]
target = 'dist/jspm.exe'
deps = ['src/jspm.js', 'package.json', 'appmap.json']
run = 'deno compile -o dist/jspm.exe --unstable -A --importmap appmap.json --no-check src/jspm.js'

[[task]]
name = 'test'
dep = 'test:'

[[task]]
name = 'test:##'
dep = 'test/##.test.js'
run = 'deno run -A $DEP'
